server:
  port: 8083 # Porta dedicada para o serviço de estoque

spring:
  application:
    name: inventory-service

  # 1. A mesma conexão com o PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5433/ecommerce
    username: admin
    password: adminpassword
    driver-class-name: org.postgresql.Driver

  # 2. Configuração do JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update # Deixa o Spring criar as tabelas de estoque para nós
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # 3. Desativando Liquibase temporariamente, igual fizemos no Order
  liquibase:
    enabled: false

# 4. Registro no Eureka para o API Gateway (e o Order) o encontrarem
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
